Repository Yangpa-NurturingPartner/AI, pull requests merged in 2024-09, with the labels that each got.

#2 [기능구현] 비디오 데이터 크롤링 및 요약 기능 구현
  video_data_preprocessing/batch_input.jsonl
  video_data_preprocessing/batch_inputs/batch_input_0.jsonl
  video_data_preprocessing/batch_inputs/batch_input_1.jsonl
  video_data_preprocessing/batch_inputs/batch_input_2.jsonl
  video_data_preprocessing/batch_inputs/batch_input_3.jsonl
  video_data_preprocessing/batch_inputs/batch_input_4.jsonl
  video_data_preprocessing/batch_inputs/batch_input_5.jsonl
  video_data_preprocessing/batch_inputs/batch_input_6.jsonl
  video_data_preprocessing/batch_inputs/batch_input_7.jsonl
  video_data_preprocessing/batch_inputs/batch_input_8.jsonl
  video_data_preprocessing/batch_result.jsonl
  video_data_preprocessing/batch_results/batch_result_0.jsonl
  video_data_preprocessing/batch_results/batch_result_1.jsonl
  video_data_preprocessing/batch_results/batch_result_2.jsonl
  video_data_preprocessing/batch_results/batch_result_3.jsonl
  video_data_preprocessing/batch_results/batch_result_4.jsonl
  video_data_preprocessing/batch_results/batch_result_5.jsonl
  video_data_preprocessing/batch_results/batch_result_6.jsonl
  video_data_preprocessing/batch_results/batch_result_7.jsonl
  video_data_preprocessing/batch_results/batch_result_8.jsonl
  video_data_preprocessing/create_batch_file.py
  video_data_preprocessing/request_batch_api.py
  video_data_preprocessing/youtube_crawling.py
Labels: 기능구현이슈, 기능설계

#4 [기능 구현] 문서 크롤링 후 요약 기능 구현
  document_crawling/blog/blog_content/blog.py
  document_crawling/blog/blog_content/blog_content.py
  document_crawling/blog/blog_content/blog_link.py
  document_crawling/blog/blog_content/blog_summary.py
  document_crawling/blog/news_make_up/blog_link.py
  document_crawling/blog/news_make_up/link_crawling.py
  document_crawling/blog/news_make_up/makeup_summary.py
  document_crawling/blog/news_make_up/news.py
  document_crawling/blog/news_make_up/news_content.py
  document_crawling/blog/news_todak/blog_link.py
  document_crawling/blog/news_todak/link_crawling.py
  document_crawling/blog/news_todak/news.py
  document_crawling/blog/news_todak/news_content.py
  document_crawling/blog/news_todak/todak_summary.py
  document_crawling/donga/content_crawling.py
  document_crawling/donga/donga.py
  document_crawling/donga/donga_summaries.xlsx
  document_crawling/donga/donga_summary.py
  document_crawling/donga/link_crawling.py
  document_crawling/qna/qna csv/summaries 4o.xlsx
  document_crawling/qna/qna csv/summaries mini test.csv
  document_crawling/qna/qna csv/summaries mini.csv
  document_crawling/qna/qna csv/summaries mini.xlsx
  document_crawling/qna/qna csv/summaries.csv
  document_crawling/qna/qna.py
  document_crawling/qna/qna_summary_test.py
Labels: 기능구현이슈, 손석현

#10 TMMCC Hybrid Search 구현 완료
  hybrid_search/hybrid_search_langchain.py
  hybrid_search/hybrid_search_opensearch.py
  video_data_db/hybrid_search_langchain.py
  video_data_db/opensearch_module/add_behavior_analysis.py
  video_data_db/opensearch_module/delete_data.py
  video_data_db/postgres_module/embedding.py
Labels: 기능구현이슈, 기능설계, 안유진

#15 통합검색, 채팅히스토리검색, 커뮤니티 검색, RAG채팅 api 구현 완료
  hybrid_search/hybrid_search_langchain.py
  search_module/search_api.py
  search_module/search_index.py
Labels: 기능구현이슈, 기능설계, 안유진
